config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs do
    resources :resumes
    collection do
      get :search
    end
  end
  root 'welcome#index'
  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
      end
      resources :resumes
    end
  end
  namespace :account do
    resources :jobs
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :wage_upper_bound, presence: true
  validates :wage_lower_bound, presence: true
  validates :wage_lower_bound, numericality: {greater_than: 0}
  validates :title, presence: true
  scope :published, -> { where(is_hidden: false) }
  scope :recent, -> { order('created_at DESC') }
  has_many :resumes
  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end
  has_many :job_relationships
  has_many :members, through: :job_relationships, source: :user
end

app/models/job_relationship.rb
class JobRelationship < ApplicationRecord
	belongs_to :user
	belongs_to :job
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  belongs_to :job
  validates :content, presence: true
  mount_uploader :attachment, AttachmentUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def admin?
    is_admin
  end
  has_many :resumes
  has_many :job_relationships
  has_many :applied_jobs, :through => :job_relationships, :source => :job 
  def has_applied?(job)
  	applied_jobs.include?(job)
  end
  def apply!(job)
  	applied_jobs << job
  end
end

app/controllers/account/jobs_controller.rb
class Account::JobsController < ApplicationController
	before_action :authenticate_user!
	def index
		@jobs = current_user.applied_jobs
	end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_is_admin
  layout "admin"
  def index
    @jobs = Job.all
  end
  def show
    @job = Job.find(params[:id])
  end
  def new
    @job = Job.new
  end
  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end
  def edit
    @job = Job.find(params[:id])
  end
  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end
  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to admin_jobs_path
  end
  def publish
    @job = Job.find(params[:id])
    @job.publish!

    redirect_to :back
  end

  def hide
    @job = Job.find(params[:id])

    @job.hide!

    redirect_to :back
  end
  private
  def job_params
    params.require(:job).permit(:title, :description, :wage_lower_bound, :wage_upper_bound, :contact_email, :is_hidden )
  end
end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin

  layout "admin"

  def index
    @job = Job.find(params[:job_id])
    @resumes = @job.resumes.order('created_at DESC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def require_is_admin
    if !current_user.admin?
      flash[:alert] = 'You are not admin'
      redirect_to root_path
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :validates_search_key, only: [:search]
  def index
    @jobs = case params[:order]
    when 'by_lower_bound'
      Job.published.order('wage_lower_bound DESC')
    when 'by_upper_bound'
      Job.published.order('wage_upper_bound DESC')
    else
      Job.published.recent
    end
  end
  def show
    @job = Job.find(params[:id])
    if @job.is_hidden
      flash[:warning] = "This Job already archieved"
      redirect_to root_path
    end
  end
  def new
    @job = Job.new
  end
  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end
  def edit
    @job = Job.find(params[:id])
  end
  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end
  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end
  def search
    if @query_string.present?
      @jobs = search_params
    end
  end
  protected
  def validates_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
  end
  private
  def job_params
    params.require(:job).permit(:title, :description, :wage_lower_bound, :wage_upper_bound, :contact_email, :is_hidden )
  end
  def search_params
    case params[:order]
    when "wage_upper_bound"
      Job.ransack({title_or_description_cont: @query_string}).result(distinct: true).published.order("wage_upper_bound DESC")
    when "wage_lower_bound"
      Job.ransack({title_or_description_cont: @query_string}).result(distinct: true).published.order("wage_lower_bound DESC")
    else
      Job.ransack({title_or_description_cont: @query_string}).result(distinct: true).published
    end
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!
  def new
    @job = Job.find(params[:job_id])
    @resume = Resume.new
  end
  def create
    @job = Job.find(params[:job_id])
    @resume = Resume.new(resume_params)
    @resume.job = @job
    @resume.user = current_user
    if @resume.save
      flash[:notice] = "Successfully submitted resume"
      redirect_to job_path(@job)
    else
      render :new
    end
  end
  private
  def resume_params
    params.require(:resume).permit(:content, :attachment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/account/jobs_helper.rb
module Account::JobsHelper
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def render_job_status(job)
    if job.is_hidden
      content_tag(:span,"", :class => "fa fa-lock")
    else
      content_tag(:span,"", :class => "fa fa-globe")
    end
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/jobs/edit.html.erb
<h1> Edit a job </h1>

<%= simple_form_for [:admin, @job] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

app/views/admin/jobs/index.html.erb
<div class="pull-right">
  <%= link_to("Add a job", new_admin_job_path, :class => "btn btn-default" ) %>
</div>
<br><br>
<table class="table table-boldered">
    <thead>
        <tr>
            <td>职缺</td>
            <td> 收到履历数量</td>
            <td>薪资下限</td>
            <td>薪资上限</td>
            <td>管理选项</td>
            <td>刊登时间</td>
        </tr>
    </thead>
    <% @jobs.each do |job| %>
    <tr>
        <td>
          <%= render_job_status(job) %>
          <%= link_to(job.title, admin_job_path(job)) %>
        </td>
        <td> <%= link_to(job.resumes.count, admin_job_resumes_path(job)) %> </td>
        <td> <%= job.wage_lower_bound %> </td>
        <td> <%= job.wage_upper_bound %> </td>
        <td>
            <%= link_to("Edit", edit_admin_job_path(job)) %>
            |
            <%= link_to("Destroy", admin_job_path(job), :method => :delete, :data => { :confirm => "Are you sure?" }) %>
            |
            <% if job.is_hidden %>
              <%= link_to("Publish", publish_admin_job_path(job) , :method => :post, :class => "btn btn-xs btn-default") %>
            <% else %>
              <%= link_to("Hide", hide_admin_job_path(job), :method => :post,  :class => "btn btn-xs btn-default") %>
            <% end %>
        </td>
        <td>
            <%= job.created_at %>
        </td>
    </tr>
    <% end %>
</table>

app/views/admin/jobs/new.html.erb
<h1> Add a job </h1>

<%= simple_form_for [:admin, @job] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

app/views/admin/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<p>
  <%= simple_format(@job.description) %>
</p>

app/views/admin/resumes/_resume.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-12">
                <h3 class="panel-title">
                    <%= resume.user.email %>
                </h3>
            </div>

        </div>
    </div>
    <div class="panel-body">
        <div class="trix-content">
            <p> <%= simple_format(resume.content) %> </p>
        </div>

        <hr>

        <% if resume.attachment.present? %>
          <i class="fa fa-paperclip"> </i>
          <%= link_to("Download Resume", resume.attachment_url) %>
        <% else %>
           No Attachment
        <% end %>
    </div>

</div>

app/views/admin/resumes/index.html.erb
<h2> <%= @job.title %> - 履历列表 </h2>

<hr>
<%= render :partial => "resume", :collection => @resumes, :as => :resume %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2016 Job Listing
        <br>Design by Chris

    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Job Listing </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                <% if !current_user %>
                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                  <li><%= link_to("登入", new_user_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                       Hi!, <%= current_user.email %>
                       <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to("My Jobs", account_jobs_path) %></li>
                      <% if current_user.admin? %>
                        <li> <%= link_to("Admin Panel", admin_jobs_path) %> </li>
                      <% end %>
                      <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                 </li>
                <% end %>
              </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/jobs/_item.html.erb
<div class="row job-item">
	<div class="col-md-6">
		<h4 class="job-title"><%= link_to(job.title, job_path(job)) %></h4>
		<%= job.wage_lower_bound %>-<%= job.wage_upper_bound %> | <%= job.created_at %> 
	</div>
</div>
<hr>

app/views/jobs/_search_bar.html.erb
<div class="row">
  <div class="col-sm-9 col-lg-8 col-lg-offset-2"> 
    <%= form_tag search_jobs_path, method: :get, class: 'jobs-search-form'  do %>
      <div class="input-group input-group-lg">
        <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="职位...">
        <span class="input-group-btn">
          <button type="submit" class="btn btn-danger">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
    <% end %>
  </div>
</div>
  

app/views/jobs/edit.html.erb
<h1> Edit a job </h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

app/views/jobs/index.html.erb
<%= render "jobs/search_bar" %>
<div class="dropdown clearfix pull-right">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      排序
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
        <li>
          <%= link_to("按照薪资下限排序", jobs_path(:order => "by_lower_bound")) %>
        </li>
        <li>
            <%= link_to("按照薪资上限排序", jobs_path(:order => "by_upper_bound")) %>

        </li>
        <li>
          <%= link_to("按照发表时间排序", jobs_path ) %>

        </li>
    </ul>
</div>
<table class="table table-boldered">
    <thead>
        <tr>
            <td>职缺</td>
            <td>薪资下限</td>
            <td>薪资上限</td>
            <td>刊登时间</td>
            <td>申请</td>
        </tr>

    </thead>
    <tbody>
        <% @jobs.each do |job| %>
        <tr>
            <td>
                <%= link_to(job.title, job_path(job)) %>
            </td>
            <td>
                <%= job.wage_lower_bound %>
            </td>
            <td>
                <%= job.wage_upper_bound %>
            </td>
            <td>
                <%= job.created_at %>
            </td>
            <td>
                <% if current_user && current_user.has_applied?(job) %>
                    <%= link_to("Has Applied", new_job_resume_path(job), class: "btn btn-info btn-sm disabled", method: :get) %>
                <% else %>
                     <%= link_to("Quick Apply", new_job_resume_path(job), class: "btn btn-info btn-sm",   method: :get) %>
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>

</table>

app/views/jobs/new.html.erb
<h1> Add a job </h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

app/views/jobs/search.html.erb
<%= render "jobs/search_bar" %>
<div class="dropdown clearfix pull-right">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      排序
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
        <li>
          <%= link_to("按照薪资下限排序", search_jobs_path(:order => "by_lower_bound")) %>
        </li>
        <li>
            <%= link_to("按照薪资上限排序", search_jobs_path(:order => "by_upper_bound")) %>

        </li>
        <li>
          <%= link_to("按照发表时间排序", search_jobs_path ) %>

        </li>
    </ul>
</div>

<div class="col-md-8 col-md-offset-2" style="margin-top: 3em;">
    <% if @jobs.present? %>
        <%= render :partial => "item", :collection => @jobs, :as => :job %>
    <% else %>
        <p>There are no jobs containing the term(s)"<%= params[:q] %>" .</p>
    <% end %>   
</div>
     

app/views/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<p>
  <%= simple_format(@job.description) %>
</p>

<div class="text-center">
  <%= link_to("投交履历", new_job_resume_path(@job), :style => "font-size: 30px; text-decoration:underline;") %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobListing2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
        <%= render "common/navbar" %>
        <%= render "common/flashes" %>
        <div class="row">
          <div class="col-md-2">
            <ul class="nav nav-pills nav-stacked" style="max-width: 300px; padding-top:20px;">
              <li class="active"><%= link_to("Jobs", admin_jobs_path ) %> </li>
            </ul>
          </div>

          <div class="col-md-10">
            <%= yield %>
          </div>
       </div>
    </div>

    <%= render "common/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobListing2</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/resumes/new.html.erb
<h3> 投交履历到 <%= @job.title %> </h3>

<hr>

<%= simple_form_for [@job, @resume] do |f| %>
  <%= f.input :content %>
  <%= f.input :attachment %>
  <%= f.submit "送出" %>
<% end %>

app/views/welcome/index.html.erb
<div id="featureBox"></div>
<div style="position:relative; width:936px; height:0px; overflow:visible; z-index:20;"><img src="//greensock.com/_img/HTML5_corner_banner.png" alt="HTML5" style="position:absolute; top:-5px; right:-5px;" /></div>
<div class="feature" id="featureAnimation">
  <div id="featureBackground" style="pointer-events:none;"></div>
  <div class="featureTextWhite" id="whyGSAP">Why GSAP?</div>
  <div class="featureTextGreen" id="performance">Performance</div>
  <div class="featureTextWhite" id="compatibility">Compatibility</div>
  <div id="browserIcons">
    <img src="//greensock.com/_img/browser-chrome-big.png" width="82" height="80" />
    <img src="//greensock.com/_img/browser-safari-big.png" width="77" height="86"  />
    <img src="//greensock.com/_img/browser-ie-big.png" width="82" height="74" />
    <img src="//greensock.com/_img/browser-firefox-big.png" width="82" height="83" />
    <img src="//greensock.com/_img/browser-opera-big.png" width="69" height="75" />
  </div>
  <div class="featureTextMinor" id="fallDown">Other tools fall down in older browsers, but GSAP is remarkably compatible.</div>
  <img id="anythingIcon" src="//greensock.com/_img/animate-anything.png" width="102" height="108" style="position:absolute; top:50px; left:143px; display:block;" />
  <div id="transformBox" style="background-color:#91e600; width:130px; height:130px; position:absolute; top:40px; left:100px;"></div>
  <div class="featureTextWhite" id="transform" style="font-size:34px; width:640px; text-align:left; left:270px; top:80px; line-height:36px;">Scale, rotate & move independently</div>
  <div class="featureTextWhite" id="transformSub" style="font-size:16px; width:420px; text-align:left; left:270px; top:122px; color:#CCCCCC;">(impossible with CSS animations/transitions)</div>
  <div class="featureTextWhite" id="anything" style="width:620px; text-align:left; left:302px; top:63px;">XNJYHQLJYQEW</div>
  <div class="featureTextWhite" id="anythingSub" style="font-size:16px; width:390px; text-align:left; left:300px; top:122px; color:#CCCCCC;">CSS, SVG, canvas libraries, colors, beziers, etc.</div>
  <div class="featureTextWhite" id="control" style="text-align: left; top:64px; left:130px;">Total control</div>
  <div class="featureTextWhite" id="controlSub" style="font-size:16px; text-align:left; left:130px; top:122px; color:#CCCCCC;">pause(), play(), reverse(), or timeScale() any tween or sequence.</div>

  <div class="featureTextWhite" id="GSAP" style="top:60px;">GSAP</div>
  <div class="featureTextMinor" id="newStandardText" style="top:125px; text-align: center; width: 936px;">The new standard for HTML5 animation</div>
  <div id="featureClick" style="position:absolute; width:936px; height:220px;"><img src="//greensock.com/_img/blank.gif" width="936" height="220" /></div>
  <div id="replay" style="text-align:right; position:absolute; left:825px; top:190px; cursor:pointer; color:#999999; font-family: 'Lucida Grande', 'Lucida Sans Unicode', Helvetica, Arial, Verdana, sans-serif; font-size:12px; width:100px; visibility:hidden;">replay <img id="replayIcon" src="//greensock.com/_img/codepen/allDevicesBanner/replay.png" width="19" height="19" style="margin-left:2px; vertical-align: middle;" /></div>
  <div id="ctrl_slider"></div>
</div>